labels:
  - name: '#817'
    color: '#881177'
  - name: '#a35'
    color: '#aa3355'
  - name: '#c66'
    color: '#cc6666'
  - name: '#e94'
    color: '#ee9944'
  - name: '#ed0'
    color: '#eedd00'
  - name: '#9d5'
    color: '#99dd55'
  - name: '#4d8'
    color: '#44dd88'
  - name: '#2cb'
    color: '#22ccbb'
  - name: '#0bc'
    color: '#00bbcc'
  - name: '#09c'
    color: '#0099cc'
  - name: '#36b'
    color: '#3366bb'
  - name: '#639'
    color: '#663399'
