labels:
  - name: '#817'
    color: '#817'
  - name: '#a35'
    color: '#a35'
  - name: '#c66'
    color: '#c66'
  - name: '#e94'
    color: '#e94'
  - name: '#ed0'
    color: '#ed0'
  - name: '#9d5'
    color: '#9d5'
  - name: '#4d8'
    color: '#4d8'
  - name: '#2cb'
    color: '#2cb'
  - name: '#0bc'
    color: '#0bc'
  - name: '#09c'
    color: '#09c'
  - name: '#36b'
    color: '#36b'
  - name: '#639'
    color: '#639'
